---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
  interval: 1m0s
  values:
    kubeProxyReplacement: true
    k8sServiceHost: api.kubernetes.homelab.veselabs.com
    k8sServicePort: 6443
    l2announcements:
      enabled: true
      k8sClientRateLimit:
        qps: 10
        burst: 20
    gatewayAPI:
      enabled: true
