{
 "title": "Kubernetes Node metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(node) (1 - rate(node_cpu_seconds_total{job=\"integrations/node_exporter\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes{job=\"integrations/node_exporter\"} / node_memory_MemTotal_bytes{job=\"integrations/node_exporter\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"integrations/node_exporter\", device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "{{node}} Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"integrations/node_exporter\", device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "{{node}} Transmit"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(node_disk_read_bytes_total{job=\"integrations/node_exporter\"}[$__rate_interval]))",
     "legendFormat": "{{node}} Read"
    },
    {
     "expr": "sum by(node) (rate(node_disk_written_bytes_total{job=\"integrations/node_exporter\"}[$__rate_interval]))",
     "legendFormat": "{{node}} Write"
    }
   ]
  }
 ]
}