---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  chart:
    spec:
      version: 3.13.0
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  interval: 1m0s
  values:
    args:
      - --kubelet-insecure-tls
