---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-slow-critical
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  dataLocality: best-effort
  diskSelector: slow
  numberOfReplicas: "3"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: longhorn-slow-standard
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  dataLocality: best-effort
  diskSelector: slow
  numberOfReplicas: "2"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-slow-single
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  dataLocality: best-effort
  diskSelector: slow
  numberOfReplicas: "1"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-slow-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  dataLocality: strict-local
  diskSelector: slow
  numberOfReplicas: "1"
