---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  chart:
    spec:
      version: v1.18.8
      chart: rook-ceph
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
  interval: 1m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  chart:
    spec:
      version: v1.18.8
      chart: rook-ceph-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
  interval: 1m0s
  values:
    route:
      dashboard:
        parentRefs:
          - name: gateway
            namespace: kube-system
        host:
          name: ceph.homelab.veselabs.com
    cephClusterSpec:
      resources:
        osd:
          limits:
            memory: 2Gi
          requests:
            memory: 2Gi
