---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr
resources:
  - ./jellyfin.yaml
  - ./namespace.yaml
  - ./prowlarr.yaml
  - ./pvc.yaml
  - ./qbittorrent.yaml
  - ./radarr.yaml
