---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: servarr
    app.kubernetes.io/instance: servarr
    app.kubernetes.io/component: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: servarr
      app.kubernetes.io/instance: servarr
      app.kubernetes.io/component: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: servarr
        app.kubernetes.io/instance: servarr
        app.kubernetes.io/component: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:6.0.4.10291-ls295
          ports:
            - name: http
              containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: servarr
    app.kubernetes.io/instance: servarr
    app.kubernetes.io/component: radarr
spec:
  selector:
    app.kubernetes.io/name: servarr
    app.kubernetes.io/instance: servarr
    app.kubernetes.io/component: radarr
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
