---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: servarr
    app.kubernetes.io/instance: servarr
    app.kubernetes.io/component: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: servarr
      app.kubernetes.io/instance: servarr
      app.kubernetes.io/component: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: servarr
        app.kubernetes.io/instance: servarr
        app.kubernetes.io/component: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:4.0.16.2944-ls304
          ports:
            - name: http
              containerPort: 8989
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: data
              mountPath: /data
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: data
          persistentVolumeClaim:
            claimName: servarr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  labels:
    app.kubernetes.io/name: servarr
    app.kubernetes.io/instance: servarr
    app.kubernetes.io/component: sonarr
spec:
  storageClassName: longhorn-slow-single
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: servarr
    app.kubernetes.io/instance: servarr
    app.kubernetes.io/component: sonarr
spec:
  selector:
    app.kubernetes.io/name: servarr
    app.kubernetes.io/instance: servarr
    app.kubernetes.io/component: sonarr
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sonarr
spec:
  parentRefs:
    - name: gateway
      namespace: kube-system
  hostnames: [sonarr.homelab.veselabs.com]
  rules:
    - backendRefs:
        - name: sonarr
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
