{
 "title": "Bare Metal / Views / Global",
 "tags": [
  "Bare Metal",
  "Prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   { "name": "resolution", "label": "Resolution", "query": "1s,15s,30s,1m,3m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Pressure (cluster)",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_pressure_cpu_waiting_seconds_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg(irate(node_pressure_memory_waiting_seconds_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Mem"
    },
    {
     "expr": "avg(irate(node_pressure_io_waiting_seconds_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "I/O"
    },
    {
     "expr": "avg(irate(node_pressure_irq_stalled_seconds_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Irq"
    }
   ]
  },
  {
   "title": "Sys Load (cluster)",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"$job\"} / (count without(cpu, mode) (node_cpu_seconds_total{job=\"$job\", mode=\"idle\"})))"
    }
   ]
  },
  {
   "title": "CPU Busy (cluster)",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "RAM Used (cluster)",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(clamp_min((1 - (node_memory_MemAvailable_bytes{job=\"$job\"} / node_memory_MemTotal_bytes{job=\"$job\"})), 0))"
    }
   ]
  },
  {
   "title": "Network Traffic (cluster)",
   "type": "stat",
   "description": "Incoming and outgoing network traffic",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{job=\"$job\", device=\"eno1\"}[$__rate_interval]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{job=\"$job\", device=\"eno1\"}[$__rate_interval]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Disk Throughput (cluster)",
   "type": "stat",
   "description": "Disk I/O throughput",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"$job\", device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"$job\", device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "Pressure (by host)",
   "type": "timeseries",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - I/O"
    },
    {
     "expr": "irate(node_pressure_irq_stalled_seconds_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Irq"
    }
   ]
  },
  {
   "title": "Sys Load (by host)",
   "type": "timeseries",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1{job=\"$job\"} / (count without(cpu, mode) (node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Busy (by host)",
   "type": "timeseries",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg by(instance) (rate(node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Used (by host)",
   "type": "timeseries",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_min((1 - (node_memory_MemAvailable_bytes{job=\"$job\"} / node_memory_MemTotal_bytes{job=\"$job\"})), 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic (by host)",
   "type": "timeseries",
   "description": "Incoming and outgoing network traffic by host",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"$job\", device=\"eno1\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"$job\", device=\"eno1\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets (by host)",
   "type": "timeseries",
   "description": "Number of network packets received and transmitted per second by host",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{job=\"$job\", device=\"eno1\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{job=\"$job\", device=\"eno1\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Saturation (by host)",
   "type": "timeseries",
   "description": "Network interface utilization as a percentage of its maximum capacity by host",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"$job\", device=\"eno1\"}[$__rate_interval])\n / ignoring(speed) node_network_speed_bytes{job=\"$job\", device=\"eno1\"}",
     "legendFormat": "{{instance}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"$job\", device=\"eno1\"}[$__rate_interval])\n / ignoring(speed) node_network_speed_bytes{job=\"$job\", device=\"eno1\"}",
     "legendFormat": "{{instance}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Errors / Drop (by host)",
   "type": "timeseries",
   "description": "Rate of packet-level errors and drops by host. Receive errors may indicate physical or driver issues; transmit errors may reflect collisions or hardware faults. Receive drops can indicate buffer overflow or driver issues; transmit drops may result from outbound congestion or queuing limits",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{job=\"$job\", device=\"eno1\"}[$__rate_interval])",
     "legendFormat": "{{instance}} Errors - Receive"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{job=\"$job\", device=\"eno1\"}[$__rate_interval])",
     "legendFormat": "{{instance}} Errors - Transmit"
    },
    {
     "expr": "rate(node_network_receive_drop_total{job=\"$job\", device=\"eno1\"}[$__rate_interval])",
     "legendFormat": "{{instance}} Drop - Receive"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{job=\"$job\", device=\"eno1\"}[$__rate_interval])",
     "legendFormat": "{{instance}} Drop - Transmit"
    }
   ]
  },
  {
   "title": "Disk Throughput (by host)",
   "type": "timeseries",
   "description": "Disk I/O throughput by host",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"$job\", device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval]) * on(device, instance) group_left(model) node_disk_info{job=\"$job\"}",
     "legendFormat": "{{instance}} {{model}} - Read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"$job\", device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval]) * on(device, instance) group_left(model) node_disk_info{job=\"$job\"}",
     "legendFormat": "{{instance}} {{model}} - Write"
    }
   ]
  },
  {
   "title": "Disk Throughput by IOps (by host)",
   "type": "timeseries",
   "description": "Disk I/O operations per second by host",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{job=\"$job\", device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval]) * on(device, instance) group_left(model) node_disk_info{job=\"$job\"}",
     "legendFormat": "{{instance}} {{model}} - Read"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{job=\"$job\", device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval]) * on(device, instance) group_left(model) node_disk_info{job=\"$job\"}",
     "legendFormat": "{{instance}} {{model}} - Write"
    }
   ]
  },
  {
   "title": "Disk Average Queue Size (by host)",
   "type": "timeseries",
   "description": "Average queue length of the requests that were issued by host",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{job=\"$job\", device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval]) * on(device, instance) group_left(model) node_disk_info{job=\"$job\"}",
     "legendFormat": "{{instance}} {{model}}"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time (by host)",
   "type": "timeseries",
   "description": "Average time for requests issued to the device to be served by host. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"$job\", device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{job=\"$job\"}[$__rate_interval]) * on(device, instance) group_left(model) node_disk_info{job=\"$job\"}",
     "legendFormat": "{{instance}} {{model}} - Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=\"$job\", device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{job=\"$job\"}[$__rate_interval]) * on(device, instance) group_left(model) node_disk_info{job=\"$job\"}",
     "legendFormat": "{{instance}} {{model}} - Write"
    }
   ]
  }
 ]
}