{
 "title": "Proxmox / Views / Global",
 "description": "Proxmox Virtual Environment Dashboard",
 "tags": [
  "Proxmox",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(target_info{job=\"proxmox-ve\"},proxmox_node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource allocation summary",
   "type": "table",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(vmid, node, name, type) (proxmox_vm_uptime_seconds{job=\"proxmox-ve\"})"
    },
    {
     "expr": "sum by(vmid) (proxmox_vm_uptime_seconds{job=\"proxmox-ve\"} > bool 0)"
    },
    {
     "expr": "sum by(vmid) (proxmox_vm_cpus_ratio{job=\"proxmox-ve\"})"
    },
    {
     "expr": "sum by(vmid) (proxmox_vm_maxmem_bytes{job=\"proxmox-ve\"})"
    },
    {
     "expr": "sum by(vmid) (proxmox_vm_mem_bytes{job=\"proxmox-ve\"} / proxmox_vm_maxmem_bytes{job=\"proxmox-ve\"} and proxmox_vm_uptime_seconds > 0)"
    },
    {
     "expr": "sum by(vmid) (proxmox_vm_maxdisk_bytes{job=\"proxmox-ve\"})"
    },
    {
     "expr": "sum by(vmid) (proxmox_vm_disk_bytes{job=\"proxmox-ve\", type=\"lxc\"} / proxmox_vm_maxdisk_bytes{job=\"proxmox-ve\", type=\"lxc\"})"
    }
   ]
  },
  {
   "title": "CPU history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "proxmox_node_cpustat_cpu_percent{job=\"proxmox-ve\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Current CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proxmox_node_cpustat_cpu_percent{job=\"proxmox-ve\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(proxmox_node_cpustat_cpus_percent{job=\"proxmox-ve\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "proxmox_node_memory_memused_bytes{job=\"proxmox-ve\"} / proxmox_node_memory_memtotal_bytes{job=\"proxmox-ve\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Current memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(proxmox_node_memory_memused_bytes{job=\"proxmox-ve\"} / proxmox_node_memory_memtotal_bytes{job=\"proxmox-ve\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(proxmox_node_memory_memused_bytes{job=\"proxmox-ve\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(proxmox_node_memory_memtotal_bytes{job=\"proxmox-ve\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(proxmox_node_memory_memtotal_bytes{job=\"proxmox-ve\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Guests CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "proxmox_vm_cpu_percent{job=\"proxmox-ve\"} and proxmox_vm_uptime_seconds > 0",
     "legendFormat": "{{node}} - {{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Guests memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "proxmox_vm_mem_bytes{job=\"proxmox-ve\"} / proxmox_vm_maxmem_bytes{job=\"proxmox-ve\"} and proxmox_vm_uptime_seconds > 0",
     "legendFormat": "{{node}} - {{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxmox_storage_used_bytes{job=\"proxmox-ve\", node=\"$instance\"} / proxmox_storage_total_bytes{job=\"proxmox-ve\", node=\"$instance\"}",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "Space allocation",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 4, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxmox_storage_used_bytes{job=\"proxmox-ve\", node=\"$instance\"}",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "LXC guests Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "proxmox_vm_disk_bytes{job=\"proxmox-ve\", type=\"lxc\"} / proxmox_vm_maxdisk_bytes{job=\"proxmox-ve\", type=\"lxc\"}",
     "legendFormat": "{{node}} - {{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(proxmox_vm_netin_bytes_total{job=\"proxmox-ve\"}[5m]) and proxmox_vm_uptime_seconds > 0",
     "legendFormat": "{{node}} - {{name}} RECV ({{type}})"
    },
    {
     "expr": "rate(proxmox_vm_netout_bytes_total{job=\"proxmox-ve\"}[5m]) and proxmox_vm_uptime_seconds > 0",
     "legendFormat": "{{node}} - {{name}} SEND ({{type}})"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(proxmox_vm_diskwrite_bytes_total{job=\"proxmox-ve\"}[5m]) + rate(proxmox_vm_diskread_bytes_total{job=\"proxmox-ve\"}[5m]) and proxmox_vm_uptime_seconds > 0",
     "legendFormat": "{{node}} - {{name}} ({{type}})"
    }
   ]
  }
 ]
}