---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  chart:
    spec:
      version: 1.5.1
      chart: alloy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1m0s
  values:
    alloy:
      configMap:
        content: |
          prometheus.remote_write "mimir" {
            endpoint {
              url = "http://mimir-gateway.monitoring.svc.cluster.local:80/api/v1/push"

              headers = {
                "X-Scope-OrgID" = "homelab",
              }
            }
          }

          prometheus.exporter.unix "default" {
          }

          prometheus.scrape "node_exporter" {
            targets    = prometheus.exporter.unix.default.targets
            forward_to = [prometheus.remote_write.default.receiver]
          }
