---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  chart:
    spec:
      version: 1.5.1
      chart: alloy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1m0s
  values:
    alloy:
      mounts:
        varlog: true
      configMap:
        content: |
          prometheus.remote_write "mimir" {
            endpoint {
              url = "http://mimir-gateway.monitoring.svc.cluster.local:80/api/v1/push"

              headers = {
                "X-Scope-OrgID" = "homelab",
              }
            }
          }

          loki.write "loki" {
            endpoint {
              url = "http://loki-gateway.monitoring.svc.cluster.local:80/loki/api/v1/push"

              headers = {
                "X-Scope-OrgID" = "homelab",
              }
            }
          }

          import.git "node_exporter" {
            repository     = "https://github.com/grafana/alloy-modules.git"
            revision       = "v0.2.11"
            path           = "modules/system/node-exporter/metrics.alloy"
            pull_frequency = "0s"
          }

          node_exporter.kubernetes "targets" {
            field_selectors = ["spec.nodeName=" + coalesce(sys.env("HOSTNAME"), constants.hostname)]
          }

          discovery.relabel "node_exporter" {
            targets = node_exporter.kubernetes.targets.output

            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label  = "node"
            }
          }

          node_exporter.scrape "metrics" {
            targets    = discovery.relabel.node_exporter.output
            forward_to = [prometheus.remote_write.mimir.receiver]
          }

          import.git "ksm" {
            repository     = "https://github.com/grafana/alloy-modules.git"
            revision       = "v0.2.11"
            path           = "modules/kubernetes/kube-state-metrics/metrics.alloy"
            pull_frequency = "0s"
          }

          ksm.kubernetes "targets" {
          }

          ksm.scrape "metrics" {
            targets    = ksm.kubernetes.targets.output
            forward_to = [prometheus.remote_write.mimir.receiver]
          }

          import.git "k8s" {
            repository     = "https://github.com/grafana/alloy-modules.git"
            revision       = "v0.2.11"
            path           = "modules/kubernetes/core/metrics.alloy"
            pull_frequency = "0s"
          }

          k8s.cadvisor "scrape" {
            field_selectors = ["metadata.name=" + coalesce(sys.env("HOSTNAME"), constants.hostname)]
            forward_to      = [prometheus.remote_write.mimir.receiver]
          }

          loki.relabel "journal" {
            forward_to = []

            rule {
              source_labels = ["__journal__hostname"]
              target_label  = "node"
            }

            rule {
              source_labels = ["__journal__systemd_unit"]
              target_label  = "unit"
            }

            rule {
              source_labels = ["__journal_priority"]
              target_label  = "priority"
            }
          }

          loki.source.journal "all" {
            path          = "/var/log/journal"
            labels        = {job = "integrations/journal"}
            relabel_rules = loki.relabel.journal.rules
            forward_to    = [loki.write.loki.receiver]
          }

          discovery.kubernetes "pods" {
            role = "pod"

            selectors {
              role  = "pod"
              field = "spec.nodeName=" + coalesce(sys.env("HOSTNAME"), constants.hostname)
            }
          }

          discovery.relabel "pods" {
            targets = discovery.kubernetes.pods.targets

            rule {
              target_label = "job"
              replacement  = "integrations/kubernetes/pods"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label  = "node"
            }

            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_controller_kind"]
              target_label  = "kind"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_controller_name"]
              target_label  = "name"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "pod"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }
          }

          loki.source.kubernetes "pods" {
            targets    = discovery.relabel.pods.output
            forward_to = [loki.write.loki.receiver]
          }

          loki.source.kubernetes_events "cluster" {
            job_name   = "integrations/kubernetes/events"
            forward_to = [loki.write.loki.receiver]
          }
