---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  chart:
    spec:
      version: 1.5.1
      chart: alloy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1m0s
  values:
    alloy:
      configMap:
        content: |
          prometheus.remote_write "mimir" {
            endpoint {
              url = "http://mimir-gateway.monitoring.svc.cluster.local:80/api/v1/push"

              headers = {
                "X-Scope-OrgID" = "homelab",
              }
            }
          }

          import.git "node_exporter" {
            repository     = "https://github.com/grafana/alloy-modules.git"
            revision       = "v0.2.11"
            path           = "modules/system/node-exporter/metrics.alloy"
            pull_frequency = "0s"
          }

          node_exporter.kubernetes "targets" {
          }

          node_exporter.scrape "metrics" {
            targets = node_exporter.kubernetes.targets.output
            forward_to = [prometheus.remote_write.mimir.receiver]
          }

          import.git "ksm" {
            repository     = "https://github.com/grafana/alloy-modules.git"
            revision       = "v0.2.11"
            path           = "modules/kubernetes/kube-state-metrics/metrics.alloy"
            pull_frequency = "0s"
          }

          ksm.kubernetes "targets" {
          }

          ksm.scrape "metrics" {
            targets    = ksm.kubernetes.targets.output
            forward_to = [prometheus.remote_write.mimir.receiver]
          }
