---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      version: 10.3.1
      chart: grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1m0s
  values:
    route:
      main:
        enabled: true
        hostnames: [grafana.homelab.veselabs.com]
        parentRefs:
          - name: gateway
            namespace: kube-system

    sidecar:
      alerts:
        enabled: true
      dashboards:
        enabled: true
      datasources:
        enabled: true
      plugins:
        enabled: true
      notifiers:
        enabled: true
