---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      version: 10.3.1
      chart: grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1m0s
  values:
    replicas: 2

    route:
      main:
        enabled: true
        parentRefs:
          - name: gateway
            namespace: kube-system
        hostnames: [grafana.homelab.veselabs.com]

    sidecar:
      alerts:
        enabled: true
      dashboards:
        enabled: true
      datasources:
        enabled: true
      plugins:
        enabled: true
      notifiers:
        enabled: true

    admin:
      existingSecret: grafana-admin-user
      userKey: username
      passwordKey: password

    extraSecretMounts:
      - name: grafana-postgresql-app
        secretName: grafana-postgresql-app
        defaultMode: 0400
        mountPath: /var/run/secrets/grafana-postgresql-app
        readOnly: true

    grafana.ini:
      database:
        type: postgres
        user: $__file{/var/run/secrets/grafana-postgresql-app/user}
        password: $__file{/var/run/secrets/grafana-postgresql-app/password}
        host: $__file{/var/run/secrets/grafana-postgresql-app/host}
        port: $__file{/var/run/secrets/grafana-postgresql-app/port}
        name: $__file{/var/run/secrets/grafana-postgresql-app/dbname}
