---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
spec:
  chart:
    spec:
      version: 6.0.5
      chart: mimir-distributed
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1m0s
  values:
    minio:
      persistence:
        size: 15Gi
      serviceAccount:
        # Both Mimir and Loki charts use `minio-sa` by default
        name: mimir-minio-sa

    mimir:
      structuredConfig:
        limits:
          compactor_blocks_retention_period: 14d

    kafka:
      persistence:
        size: 15Gi

    ingester:
      persistentVolume:
        size: 6Gi

    alertmanager:
      persistentVolume:
        storageClass: longhorn-r1
