---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
spec:
  chart:
    spec:
      version: 6.0.5
      chart: mimir-distributed
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1m0s
  timeout: 10m0s
  values:
    mimir:
      structuredConfig:
        limits:
          compactor_blocks_retention_period: 90d

    minio:
      persistence:
        storageClass: longhorn-slow-single
        size: 60Gi
      serviceAccount:
        # Both Mimir and Loki charts use `minio-sa` by default
        name: mimir-minio-sa

    kafka:
      persistence:
        storageClassName: longhorn-slow-single
        size: 30Gi

    alertmanager:
      persistentVolume:
        storageClass: longhorn-slow-single

    compactor:
      persistentVolume:
        storageClass: longhorn-slow-single
        size: 6Gi

    ingester:
      replicas: 3
      zoneAwareReplication:
        enabled: false
      persistentVolume:
        storageClass: longhorn-slow-single
        size: 4Gi

    store_gateway:
      replicas: 3
      zoneAwareReplication:
        enabled: false
      persistentVolume:
        storageClass: longhorn-slow-single
