---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  labels:
    grafana_datasource: "true"
  disableNameSuffixHash: true
configMapGenerator:
  - name: grafana-datasource.loki
    files: [./loki.yaml]

  - name: grafana-datasource.prometheus
    files: [./prometheus.yaml]
